server:
  port: 9090
  basepackage: com.xzcode.socket.hw
  host: localhost
  appname: files-service

spring: 
  application:
    name: ${server.appname}
  profiles:
    active: dev


sourcemuch:
  commons:
    jdbclink:
      enabled: true
      scanPackage: ${server.basepackage}.entity
    socket:
      enabled: true
      autoRun: false
      host: 127.0.0.1                       
      port: 9999                              
      bossThreadSize: 0                       
      workThreadSize: 0                       
      corePoolSize: 10                        
      maximumPoolSize: 100                    
      keepAliveTime: 10000                    
      taskQueueSize: 100                      
      scanPackage: ${server.basepackage}
      idleCheckEnabled: true                  
      readerIdleTime: 5000                    
      writerIdleTime: 5000                    
      allIdleTime: 5000                       
      maxHeartBeatLoseTimes: 3                
      serverType: websocket
      serializerType: msgpack
      websocketPath: /websocket             
      httpMaxContentLength: 65536  
    datasource:
      hikari: 
        enabled: true
        jdbcUrl: jdbc:mysql://${server.host}:3306/hellowork?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        username: root
        password: root
        properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            useLocalTransactionState: true
            rewriteBatchedStatements: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false  

#mybatis
mybatis:
  type-aliases-package: ${server.basepackage}.entity
  mapper-locations: classpath*:mappers/**/*.xml
    
    

logging:
  file: /app/logs/${server.appname}/${server.appname}.log
  level: 
    root: debug
